name: Releases

on: 
  push:
    tags:
    - 'v1.0.1'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "dist/qikqr-1.0.1.AppImage,qikqr_1.0.1_amd64.deb,qikqr-1.0.1.tar.xz"
        token: ${{ secrets.GITHUB_TOKEN }}
